CREATE TABLE `sap-sales-inquiry-header-data`
(
  `SalesInquiry`                    varchar(10) NOT NULL,
  `SalesInquiryType`                varchar(4) DEFAULT NULL,
  `SalesOrganization`               varchar(4) DEFAULT NULL,
  `DistributionChannel`             varchar(2) DEFAULT NULL,
  `OrganizationDivision`            varchar(2) DEFAULT NULL,
  `SalesGroup`                      varchar(3) DEFAULT NULL,
  `SalesOffice`                     varchar(4) DEFAULT NULL,
  `SalesDistrict`                   varchar(6) DEFAULT NULL,
  `SoldToParty`                     varchar(10) DEFAULT NULL,
  `CreationDate`                    date DEFAULT NULL,
  `LastChangeDate`                  date DEFAULT NULL,
  `PurchaseOrderByCustomer`         varchar(35) DEFAULT NULL,
  `CustomerPurchaseOrderType`       varchar(4) DEFAULT NULL,
  `CustomerPurchaseOrderDate`       date DEFAULT NULL,
  `SalesInquiryDate`                date DEFAULT NULL,
  `TotalNetAmount`                  varchar(13) DEFAULT NULL,
  `TransactionCurrency`             varchar(5) DEFAULT NULL,
  `SDDocumentReason`                varchar(3) DEFAULT NULL,
  `PricingDate`                     date DEFAULT NULL,
  `HeaderBillingBlockReason`        varchar(2) DEFAULT NULL,
  `BindingPeriodValidityStartDate`  date DEFAULT NULL,
  `BindingPeriodValidityEndDate`    date DEFAULT NULL,
  `HdrOrderProbabilityInPercent`    varchar(3) DEFAULT NULL,
  `ExpectedOrderNetAmount`          varchar(13) DEFAULT NULL,
  `IncotermsClassification`         varchar(3) DEFAULT NULL,
  `CustomerPaymentTerms`            varchar(4) DEFAULT NULL,
  `PaymentMethod`                   varchar(1) DEFAULT NULL,
  `OverallSDProcessStatus`          varchar(1) DEFAULT NULL,
  `TotalCreditCheckStatus`          varchar(1) DEFAULT NULL,
  `OverallSDDocumentRejectionSts`   varchar(1) DEFAULT NULL,
    PRIMARY KEY (`SalesInquiry`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
